# Generated by Django 3.2.5 on 2021-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_body", models.TextField()),
                ("text_url", models.SlugField(max_length=10)),
                ("text_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
