# Generated by Django 3.2.5 on 2021-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastebin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="text_url",
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
