# Generated by Django 3.2.5 on 2021-07-24 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="topic_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
    ]
