# Generated by Django 3.2.5 on 2021-07-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20210724_0610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="topic_date",
            field=models.DateTimeField(verbose_name="date published"),
        ),
    ]
